#!/bin/bash
# configure-nebius.sh
# Reads secrets.nebius.env and regenerates all overlay files + .env.production
# Run this once after changing DOMAIN or any other value in secrets.nebius.env.

set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/secrets.nebius.env"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "❌ Not found: $ENV_FILE"
  exit 1
fi

# Load variables
source "$ENV_FILE"

# DOMAIN can be either:
#   - a nip.io address: <LB-IP>.nip.io  → <APP_SUBDOMAIN>.<LB-IP>.nip.io
#   - a real domain:    collective-museum.com   → collective-museum.com  (APP_SUBDOMAIN empty)
#
# APP_SUBDOMAIN  = frontend subdomain. Leave empty to serve from root domain.
# API_SUBDOMAIN  = API subdomain (default: api)
# Tenant pods always use their own subdomain directly under BASE_DOMAIN.
if [[ "$DOMAIN" == *.nip.io ]]; then
  BASE_DOMAIN="$DOMAIN"
else
  BASE_DOMAIN="$DOMAIN"
fi

API_SUB="${API_SUBDOMAIN:-api}"

# Empty APP_SUBDOMAIN = serve frontend from root domain (e.g. collective-museum.com)
if [[ -z "${APP_SUBDOMAIN:-}" ]]; then
  PORTAL_HOST="${BASE_DOMAIN}"
else
  PORTAL_HOST="${APP_SUBDOMAIN}.${BASE_DOMAIN}"
fi
API_HOST="${API_SUB}.${BASE_DOMAIN}"
CERT_ISSUER="${CERT_ISSUER:-letsencrypt}"

echo "▶️  Configuring Nebius deployment"
echo "   BASE_DOMAIN   = $BASE_DOMAIN"
echo "   PORTAL_HOST   = $PORTAL_HOST"
echo "   API_HOST      = $API_HOST"
echo "   CERT_ISSUER   = $CERT_ISSUER"
echo ""

OVERLAY="$SCRIPT_DIR/k8s/overlays/nebius"

# ── patch-backend-env.yaml ─────────────────────────────────────────────────
cat > "$OVERLAY/patch-backend-env.yaml" <<EOF
# Strategic merge patch — merges env[] by name, so only these two keys are overridden.
# The rest of the container spec (secrets, image, probes) is inherited from base unchanged.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-backend
  namespace: ca-system
spec:
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: BASE_DOMAIN
          value: "${BASE_DOMAIN}"
        - name: CA_CERT_ISSUER
          value: "${CERT_ISSUER}"
        - name: APP_URL
          value: "https://${PORTAL_HOST}"
EOF

# ── patch-backend-ingress.yaml ─────────────────────────────────────────────
cat > "$OVERLAY/patch-backend-ingress.yaml" <<EOF
# JSON patch — replaces specific fields in the saas-backend Ingress.
# ~1 is the JSON Pointer escape for / in annotation keys.
- op: replace
  path: /metadata/annotations/cert-manager.io~1cluster-issuer
  value: ${CERT_ISSUER}
- op: replace
  path: /metadata/annotations/nginx.ingress.kubernetes.io~1cors-allow-origin
  value: "https://${PORTAL_HOST}"
- op: replace
  path: /spec/tls/0/hosts/0
  value: "${API_HOST}"
- op: replace
  path: /spec/rules/0/host
  value: "${API_HOST}"
EOF

# ── patch-portal-configmap.yaml ────────────────────────────────────────────
cat > "$OVERLAY/patch-portal-configmap.yaml" <<EOF
# Strategic merge patch — overrides only the URL keys; APP_NAME is inherited from base.
apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-portal-config
  namespace: ca-system
data:
  NEXT_PUBLIC_API_URL: "https://${API_HOST}"
  NEXT_PUBLIC_WS_URL: "wss://${API_HOST}"
  NEXT_PUBLIC_APP_URL: "https://${PORTAL_HOST}"
EOF

# ── patch-portal-ingress.yaml ──────────────────────────────────────────────
cat > "$OVERLAY/patch-portal-ingress.yaml" <<EOF
# JSON patch — replaces specific fields in the customer-portal Ingress.
- op: replace
  path: /metadata/annotations/cert-manager.io~1cluster-issuer
  value: ${CERT_ISSUER}
- op: replace
  path: /spec/tls/0/hosts/0
  value: "${PORTAL_HOST}"
- op: replace
  path: /spec/rules/0/host
  value: "${PORTAL_HOST}"
EOF

# ── customer-portal/.env.production ────────────────────────────────────────
cat > "$SCRIPT_DIR/customer-portal/.env.production" <<EOF
# ============================================================
# PRODUCTION — Nebius deployment
# This file is gitignored. Generated by configure-nebius.sh
# ============================================================
NEXT_PUBLIC_API_URL=https://${API_HOST}
NEXT_PUBLIC_WS_URL=wss://${API_HOST}
NEXT_PUBLIC_APP_URL=https://${PORTAL_HOST}
NEXT_PUBLIC_APP_NAME=Collective Access Portal
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
EOF

echo "✅ Generated:"
echo "   $OVERLAY/patch-backend-env.yaml"
echo "   $OVERLAY/patch-backend-ingress.yaml"
echo "   $OVERLAY/patch-portal-configmap.yaml"
echo "   $OVERLAY/patch-portal-ingress.yaml"
echo "   customer-portal/.env.production"
echo ""
echo "Next steps:"
echo "  1. kubectl apply: kustomize build --load-restrictor LoadRestrictionsNone k8s/overlays/nebius/ | kubectl apply -f -"
echo "  2. If portal URLs changed: rebuild portal image + kubectl rollout restart deployment/customer-portal -n ca-system"
